import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import ClientLayout from "./layout.client";

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="id">
      <head>
        <link
          href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
          rel="stylesheet"
        />
      </head>
      <body className={lato.className}>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
